"""change provincial_constituency to integer

Revision ID: 79ce1cdc997f
Revises: 44fa210902ad
Create Date: 2025-11-21 16:11:02.715982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ce1cdc997f'
down_revision: Union[str, Sequence[str], None] = '44fa210902ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'provincial_constituency',
                   existing_type=sa.VARCHAR(),
                   type_=sa.Integer(),
                   postgresql_using='provincial_constituency::integer')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate', 'provincial_constituency',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
