"""Add new Candidate fields

Revision ID: d56473c1b549
Revises: 5bb846450967
Create Date: 2025-10-27 14:16:25.027916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd56473c1b549'
down_revision: Union[str, Sequence[str], None] = '5bb846450967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('election_id', sa.BigInteger(), nullable=False, comment='Reference to election table if needed'))
    op.add_column('candidate', sa.Column('birthplace', sa.String(length=255), nullable=True))
    op.add_column('candidate', sa.Column('election_year', sa.Integer(), nullable=True))
    op.add_column('candidate', sa.Column('election_level', sa.String(length=100), nullable=True))
    op.add_column('candidate', sa.Column('sources', sa.String(length=500), nullable=True, comment='Sources of candidate data'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'sources')
    op.drop_column('candidate', 'election_level')
    op.drop_column('candidate', 'election_year')
    op.drop_column('candidate', 'birthplace')
    op.drop_column('candidate', 'election_id')
    # ### end Alembic commands ###
